global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'authserver'      # burayı istediğin job_name ile değiştir
    metrics_path: /metrics
    static_configs:
      - targets: ['<service-name>:<port>']
